version: "3.7"

services:
  eventourdb: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_eventour
    restart: always
    ports: 
      - 5532:5432
    environment:
      - POSTGRES_USER=vinicius
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eventour
    volumes:
      - pgdata:/data/postgreseventour

  eventourapp:
    build: .
    container_name: appeventour
    restart: always
    ports: 
      - 3010:3010
    volumes:
      - ./usr/app
    links:
      - eventourdb
    depends_on:
      - eventourdb   

volumes:
  pgdata:
    driver: local